# Test: exact same as test.conf but with 8 principals
test_bft
2
1800000
8
239.255.0.1 5678
localhost 127.0.0.1 5679 /home/phukrit7171/Development/TinyBFT/test_runtime/priv/r0.pem
localhost 127.0.0.1 5680 /home/phukrit7171/Development/TinyBFT/test_runtime/priv/r1.pem
localhost 127.0.0.1 5681 /home/phukrit7171/Development/TinyBFT/test_runtime/priv/r2.pem
localhost 127.0.0.1 5682 /home/phukrit7171/Development/TinyBFT/test_runtime/priv/r3.pem
localhost 127.0.0.1 5683 /home/phukrit7171/Development/TinyBFT/test_runtime/priv/client0.pem
localhost 127.0.0.1 5684 /home/phukrit7171/Development/TinyBFT/test_runtime/priv/r0.pem
localhost 127.0.0.1 5685 /home/phukrit7171/Development/TinyBFT/test_runtime/priv/r1.pem
localhost 127.0.0.1 5686 /home/phukrit7171/Development/TinyBFT/test_runtime/priv/r2.pem
5000
150
60000
