#include "hmac.h"
#ifndef _Principal_h
#define _Principal_h 1

#include <mbedtls/ctr_drbg.h>
#include <string.h>
#include <sys/time.h>

#include "Time.h"
#include "mem_statistics_guard.h"
#include "public_key.h"
#include "th_assert.h"
#include "types.h"

namespace libbyzea {

class Reply;

// Sizes in bytes.
const int HMAC_size = 32;
const int UNonce_size = sizeof(long long);
const int MAC_size = HMAC_size + UNonce_size;

const int Key_size = 32;
const int Key_size_u = Key_size / sizeof(unsigned);

class Principal {
 public:
  Principal(MEM_STATS_PARAM int i, Addr a, mbedtls_ctr_drbg_context *dbrg,
            char *key_filname = nullptr);
  // Requires: "pkey" points to a file that holds the public key in PEM encoding
  // or is null or is null (in which case no public-key is associated with the
  // principal.) Effects: Creates a new Principal object.

  ~Principal();
  // Effects: Deallocates all the storage associated with principal.

  int pid() const;
  // Effects: Returns the principal identifier.

  const Addr *address() const;
  // Effects: Returns a pointer to the principal's address.

  //
  // Cryptography:
  //
  void set_in_key(const unsigned *k);
  // Effects: Sets the session key for incoming messages, in-key, from
  // this principal.

  bool verify_mac_in(const char *src, unsigned src_len, const char *mac);
  // Effects: Returns true iff "mac" is a valid MAC generated by
  // in-key for "src_len" bytes starting at "src".

  bool verify_mac_in(const char *src, unsigned src_len, const char *mac,
                     const char *unonce);
  // Effects: Returns true iff "mac" is a valid MAC generated by
  // in-key for "src_len" bytes starting at "src".

  void gen_mac_in(const char *src, unsigned src_len, char *dst,
                  const char *unonce);

  void gen_mac_in(const char *src, unsigned src_len, char *dst);
  // Requires: "dst" can hold at least "MAC_size" bytes.
  // Effects: Generates a MAC (with MAC_size bytes) using in-key and
  // places it in "dst".  The MAC authenticates "src_len" bytes
  // starting at "src".

  bool verify_mac_out(const char *src, unsigned src_len, const char *mac);
  // Effects: Returns true iff "mac" is a valid MAC generated by
  // out-key for "src_len" bytes starting at "src".

  bool verify_mac_out(const char *src, unsigned src_len, const char *mac,
                      const char *unonce);
  // Effects: Returns true iff "mac" is a valid MAC generated by
  // out-key for "src_len" bytes starting at "src".

  void gen_mac_out(const char *src, unsigned src_len, char *dst,
                   const char *unonce);

  inline static long long new_umac_nonce() { return ++umac_nonce; }

  void gen_mac_out(const char *src, unsigned src_len, char *dst);
  // Requires: "dst" can hold at least "MAC_size" bytes.
  // Effects: Generates a MAC (with MAC_size bytes) and
  // out-key and places it in "dst".  The MAC authenticates "src_len"
  // bytes starting at "src".

  ULong last_tstamp() const;
  // Effects: Returns the last timestamp in a new-key message from
  // this principal.

  void set_out_key(unsigned *k, ULong t);
  // Effects: Sets the key for outgoing messages to "k" provided "t"
  // is greater than the last value of "t" in a "set_out_key" call.

  bool is_stale(Time *tv) const;
  // Effects: Returns true iff tv is less than my_tstamp

  size_t sig_size() const;
  // Effects: Returns the size of signatures generated by this principal.

  bool verify_signature(const char *src, unsigned src_len, const char *sig,
                        bool allow_self = false);
  // Requires: "sig" is at least sig_size() bytes.
  // Effects: Checks a signature "sig" (from this principal) for
  // "src_len" bytes starting at "src". If "allow_self" is false, it
  // always returns false if "this->id == node->id()"; otherwise,
  // returns true if signature is valid.

  unsigned encrypt(const char *src, uint32_t src_len, char *dst,
                   unsigned dst_len);
  // Effects: Encrypts "src_len" bytes starting at "src" using this
  // principal's public-key and places up to "dst_len" of the result in "dst".
  // Returns the number of bytes placed in "dst".

  Request_id last_fetch_rid() const;
  void set_last_fetch_rid(Request_id r);
  // Effects: Gets and sets the last request identifier in a fetch
  // message from this principal.

 private:
  int id;
  Addr addr;
  PublicKey *pkey;
  mbedtls_ctr_drbg_context *drbg_ctx;
  size_t ssize;  // signature size
  unsigned
      kin[Key_size_u];  // session key for incoming messages from this principal
  unsigned
      kout[Key_size_u];  // session key for outgoing messages to this principal
  ULong tstamp;    // last timestamp in a new-key message from this principal
  Time my_tstamp;  // my time when message was accepted

  Request_id
      last_fetch;  // Last request_id in a fetch message from this principal

  // HMAC contexts used to generate MACs for incoming and outgoing messages
  Hmac hmac_in;
  Hmac hmac_out;

  bool verify_mac(const char *src, unsigned src_len, const char *mac,
                  const char *unonce, Hmac &hmac);
  // Requires: "ctx" points to a initialized UMAC context
  // Effects: Returns true iff "mac" is a valid MAC generated by
  // key "k" for "src_len" bytes starting at "src".

  void gen_mac(const char *src, unsigned src_len, char *dst, const char *unonce,
               Hmac &hmac);
  // Requires: "dst" can hold at least "MAC_size" bytes and ctx points to a
  // initialized UMAC context.
  // Effects: Generates a UMAC and places it in "dst".  The MAC authenticates
  // "src_len" bytes starting at "src".

  static long long umac_nonce;
};

inline const Addr *Principal::address() const { return &addr; }

inline int Principal::pid() const { return id; }

inline ULong Principal::last_tstamp() const { return tstamp; }

inline bool Principal::is_stale(Time *tv) const {
  return lessThanTime(*tv, my_tstamp);
}

inline size_t Principal::sig_size() const { return ssize; }

inline bool Principal::verify_mac_in(const char *src, unsigned src_len,
                                     const char *mac) {
  return verify_mac(src, src_len, mac + UNonce_size, mac, hmac_in);
}

inline bool Principal::verify_mac_in(const char *src, unsigned src_len,
                                     const char *mac, const char *unonce) {
  return verify_mac(src, src_len, mac, unonce, hmac_in);
}

inline void Principal::gen_mac_in(const char *src, unsigned src_len,
                                  char *dst) {
  ++umac_nonce;
  memcpy(dst, (char *)&umac_nonce, UNonce_size);
  dst += UNonce_size;
  gen_mac(src, src_len, dst, (char *)&umac_nonce, hmac_in);
}

inline void Principal::gen_mac_in(const char *src, unsigned src_len, char *dst,
                                  const char *unonce) {
  gen_mac(src, src_len, dst, unonce, hmac_in);
}

inline bool Principal::verify_mac_out(const char *src, unsigned src_len,
                                      const char *mac) {
  return verify_mac(src, src_len, mac + UNonce_size, mac, hmac_out);
}

inline bool Principal::verify_mac_out(const char *src, unsigned src_len,
                                      const char *mac, const char *unonce) {
  return verify_mac(src, src_len, mac, unonce, hmac_out);
}

inline void Principal::gen_mac_out(const char *src, unsigned src_len,
                                   char *dst) {
  ++umac_nonce;
  memcpy(dst, (char *)&umac_nonce, UNonce_size);
  dst += UNonce_size;
  gen_mac(src, src_len, dst, (char *)&umac_nonce, hmac_out);
}

inline void Principal::gen_mac_out(const char *src, unsigned src_len, char *dst,
                                   const char *unonce) {
  gen_mac(src, src_len, dst, unonce, hmac_out);
}

inline Request_id Principal::last_fetch_rid() const { return last_fetch; }

inline void Principal::set_last_fetch_rid(Request_id r) { last_fetch = r; }

/** @brief Place a new random secret key with size Keys_size in k. */
void random_key(unsigned *k);

/** @brief Return a new random integer. */
int random_int();

}  // namespace libbyzea

#endif  // _Principal_h
